version: '2'
services:
  apache_with_php:
    build: .
    volumes:
      - ./src:/var/www/html/
    ports:
      - "80:80"
    network_mode: "host" # expose in the native network namespace of the host; this way, xdebug (within the container) can connect to IDEA's xdebug server (port 9000 by default)
  mysql:
    image: mysql:5.6.33
    volumes:
      #execute the contained sql files on startup
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "comment-sidecar"
  mailhog:
      image: mailhog/mailhog:v1.0.0
      ports:
        - "1025:1025"
        - "8025:8025"